### ISSUE TITLE
npm install build fails

### ISSUE THREAD

**Issue by MarcFletcher** [psquickitjayant/S3ToLoggly#1]
Project appears to be missing package.json.

log:

```
npm install
install Couldn't read dependencies
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! path /Users/Build/GitHub/S3ToLoggly/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/Users/MarcF/GitHub/S3ToLoggly/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

**Comment by varshneyjayant** [comment]
package.json added

Thanks @Karnifexx , I forgot to add. It should work now.

**Comment by varshneyjayant** [comment]
@Karnifexx  please let me know if it works for you

**Comment by MarcFletcher** [comment]
I've just tried setting up this lamda function but am still running into problems. I am using our current ELB logs as a test (I am aware the ELB logs would not be parsed by loggly, I am just using them to see if the process works).

The Lamda function appears to run on every new PUT but the cloudwatch log is showing the following error (I apologise for the screen shot but there does not appear to be a sensible way to COPY/PASTE the logs (i've deleted the bucket name from the screenshot):

![screen shot 2015-07-15 at 13 45 41](https://cloud.githubusercontent.com/assets/3837303/8698772/a7905d1a-2af8-11e5-8be6-00d8fcbb0b3f.png)

Here is my bucket tag config:

![screen shot 2015-07-15 at 13 57 03](https://cloud.githubusercontent.com/assets/3837303/8698900/741946f8-2af9-11e5-8f59-1fd17a41ccac.png)

I have also confirmed that the iam role can access the log files by using the role to access the same file via the S3 API.

**Comment by varshneyjayant** [comment]
try https://github.com/cboscolo/elb2loggly @Karnifexx  for elb

**Comment by MarcFletcher** [comment]
I have and it suffer from the same problem as I have given here. Given you have been very helpful so far I felt bringing the problem up here when using S3ToLoggly would help me resolve it as quickly as possible.

**Comment by varshneyjayant** [comment]
hey @karnifexx, sorry I was bit busy. I will look into your issue and try to bring some solution to you.

**Comment by MarcFletcher** [comment]
Regarding this issue it was neccessary to change the IAM policy for the s3 execution role:

Change:
"s3:GetObject",
to:
"s3:Get*",
