### ISSUE TITLE
default IAM role created from README doesn't have permission for getBucketTagging

### ISSUE THREAD

**Issue by ericcj** [psquickitjayant/S3ToLoggly#2]
in the window it opens you need to do:

View Policy Document -> Edit -> add "s3:GetBucketTagging" next to "s3:PutOjbect"

**Comment by jobevers** [comment]
I had the same issue.  Though, my IAM role only needed s3:GetBucketTagging and s3:GetObject

**Comment by varshneyjayant** [comment]
added Amazons3fullaccess policy to add in docs
